### ISSUE TITLE
Implement the `certificate_transfer` interface in the Lego charms

### ISSUE THREAD

**Issue by saltiyazan** [canonical/lego-base-k8s-operator#139]
### Enhancement Proposal

In some cases charms can require the CA certificate to trust it without requiring a certificate from the provider. The Lego charms should implement the `certificate_transfer` interface to send the CA certificate and the CA chain to the requiring charms.

Initially reported by @nsklikas [here](https://matrix.to/#/!yAkGlrYcBFYzYRvOlQ:ubuntu.com/$SzIhPudq1t6416QLkvfAB0hUDPasGe47fUVRHmA8U6Q?via=ubuntu.com&via=matrix.org&via=gnome.org).

**Comment by saltiyazan** [comment]
I created this issue here because it makes sense to have the enhancement in all of our Lego charms.

**Comment by gruyaume** [comment]
I moved this to the top of our backlogs, this should be completed in the next 2 weeks.

**Comment by kayra1** [comment]
Closing, as this was fixed by @saltiyazan in PR #157
